version: '3.9'
services:
  jenkins-agent:
    image: jenkins-agent-ubuntu:22.04.1-1
    build: agent
    container_name: jenkins-agent
    restart: unless-stopped
    networks:
      - jenkins-agent
    ports:
      - 4444:22
    volumes:
      - jenkins-docker-certs:/certs/client
    environment:
      - TZ=Asia/Bangkok
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: unless-stopped
    volumes:
      - jenkins-docker-certs:/certs/client
    networks:
      jenkins:
          aliases:
            - docker
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    ports:
      - 2376:2376
    
volumes:
  jenkins-docker-certs:
    driver: overlay2